// <auto-generated />
namespace HTTP5204_PassionProject_N01437602.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v6));
        
        string IMigrationMetadata.Id
        {
            get { return "202103042015272_v6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
